497 gif images
baires/shouldideploy pull request #526
Opened 2021-07-15 14:08 UTC by HarshaVardhanNakkina

add gif images to the reasons
- added a separate file for reasons with gifs because I thought it'll be easier to verify, you can delete the original file while merging, if you like the changes
- selects a random gif URL from a pre-defined array of URLs
- displays gif below the reason
- and some style changes to make the gif look good
- fixed a file name typo

2021-07-16 10:17 UTC, HarshaVardhanNakkina commented
tenor images seem to be faster than giphy, we might want to replace giphy URLs with tenor ones

2021-07-19 12:20 UTC, baires requested changes

2021-07-19 12:20 UTC, baires commented on component/widget.js
> +        <img className="gif-reason" src={gifUrl} alt={reasonText} />
We can use `next/image` here to have Image Optimization out of the box

2021-07-19 12:20 UTC, baires commented on pages/api/index.js
> +    message: getRandom(dayHelper(time)).reason
We can include the gif as well here

2021-07-19 12:20 UTC, baires commented on pages/api/slack/index.js
> +          ? getRandom(dayHelper(time)).reason
Same as before

2021-07-19 12:22 UTC, baires commented
I really appreciate the hard work here. Im gonna keep this PR open for now I want to re-think a little more the whole idea/layout now that you include images.

2023-03-23 12:58 UTC, closed without merging