Update reasons.js
baires/shouldideploy pull request #792
Opened 2022-12-30 13:15 UTC by sonic182

More reasons not to deploy

2023-01-02 13:42 UTC, baires requested changes

2023-01-02 13:42 UTC, baires commented on helpers/reasons.js
> +  'You like fire don't you?'
You need to scape `'`

2023-01-02 13:59 UTC, sonic182 commented on helpers/reasons.js
> +  'You like fire don't you?'
Done

2023-01-03 12:36 UTC, baires approved these changes

2023-01-03 12:39 UTC, merged