feat: migrate pages files
baires/shouldideploy pull request #843
Opened 2023-02-19 14:56 UTC by dennissiq

## Proposed Changes
- Add types in all necessary places
- #830 
- #828 
- #829

2023-02-20 15:06 UTC, baires requested changes
Looking good but we need to fix its-friday class to respect the current day

2023-02-20 15:06 UTC, baires commented on pages/index.tsx
> +      <div className={`wrapper ${!shouldIDeploy(now) && 'its-friday'}`}>
This return `its-friday` always

2023-02-21 21:03 UTC, dennissiq commented on pages/index.tsx
> +      <div className={`wrapper ${!shouldIDeploy(now) && 'its-friday'}`}>
@baires can you write a suggestion to solve this? In this file, I've maintained the same logic of `pages.js`

2023-02-24 13:26 UTC, baires commented on pages/index.tsx
> +      <div className={`wrapper ${!shouldIDeploy(now) && 'its-friday'}`}>
Let me look at this over the weekend

2023-03-13 11:16 UTC, baires commented
#### 📝 Changed routes:


| [**/**](https://shouldideploy-ncymgwlk5-sgavel.vercel.app/) |
|:-:|
|<a href="https://shouldideploy-ncymgwlk5-sgavel.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/tPwpsCwMhCY1sno_DY_8ZNrdT226hBwIwjntrRLlBsqZyUgjU8Dua2oKFbXrWD6X37KWEj4EWG4xmo9b9u6j4g.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/HqAlgowH9I3-qLbUVE-4VZ_PGGtQMJOYABr5iOaf35DMP1d4lsLqc15lW7_SCaeTJIs9Ii4NG57VLZsujfH83g.png">(view full size)</a> |





1 deleted route:
- **/**

Commit e49fef6389cb02b052f2227bc51d8f50d37023c9 (https://shouldideploy-ncymgwlk5-sgavel.vercel.app).

2023-03-13 11:53 UTC, baires commented on pages/index.tsx
> +      <div className={`wrapper ${!shouldIDeploy(now) && 'its-friday'}`}>
Sorry for the delay, after a deeper look seems a false alarm, not sure why vercel cached some files. I just noticed that `timezone` is undefined now, affecting the footer (`timezone.tsx`)

2023-03-13 15:57 UTC, dennissiq commented on pages/index.tsx
> +      <div className={`wrapper ${!shouldIDeploy(now) && 'its-friday'}`}>
@baires Oh, no problems :)

Can you approve this PR?

2023-03-16 13:22 UTC, merged